---
layout: cv
title: Jackson Aden's CV
---
# Jackson Aden
Software Developer, Student, Actor, and Homie!

<div id="webaddress">
  <a href="https://www.linkedin.com/in/jackson-aden-a429a12b3/">My LinkedIn page</a>
<!-- | <a href="https://github.com/BearBait16/jacksonaden.github.io/blob/main/Jackson-Aden-Resume.pdf">Download PDF</a> -->
| <a href="https://github.com/BearBait16/jacksonaden.github.io/blob/main/Jackson-Aden-Resume.pdf">Download PDF</a>
</div>


## Currently

Figuring out how Quarto works

### Specialized in

Software Architecture, Data Analysis, and implementation of Sentiment Analysis ML models


### Research interests

AI, CI/CD pipelines, automated tasks using bash, micro-services, and game modding


## Education

`2020`
__Lone Peak High School Graduate__

`2023 - 2026`
__Brigham Young University Idaho__

- Graduated in Software Engineering with a Software Architecture and Data Science Certificate

### Profeciencies
- Python
- C++
- C#
- Google Cloud and AWS
- Bash
- Hugging Face
- Ollama 
- Git

### Internships

`Summer 2024`
Studied AI implementation in reading documentation, sentiment analysis, and learned simple full stack development principles.

`Summer 2025`
Researched and prototyped a ML alternative for a service provided by the product. Learned how to present in a convincing way,
and worked on front end and backend tickets. 

## Employment History

`Fall 2024 - Winter 2025`
__Data Entry Clerk__, BYU Idaho Alumni Office

- Figured out the most effecient ways to update records in the environment
- Learned how to work alongside people, even if we were working on different things
- Gained intrest in automating data entry jobs

`April 13 - Current`
__Junior Engineer__, Kenect
- Working on the AI platform team, finding best ways to implement ML's and LLM's in the current product
- Working part time as I graduate, then full time when I do
- Working closely with a team, helping where I can



<!-- ### Footer

Last updated: May 2013 -->